/**
 * Offline mock dataset — used only when Supabase env vars are absent (see supabase.ts).
 *
 * Lets you preview the full UI with `npm run dev` and zero external setup. The shapes
 * mirror supabase/schema.sql and lib/types.ts exactly, so pages/components are untouched.
 * `image_url` is intentionally null everywhere so cards use the built-in gradient
 * fallback and the preview works fully offline (no remote image fetches).
 */
import type { Technology, Update, Opportunity } from "./types";

const now = "2026-06-30T08:00:00.000Z";

export const mockTechnologies: Technology[] = [
  {
    id: "t-claude",
    slug: "claude-opus",
    name: "Claude Opus",
    category: "Frontier Models",
    tagline: "Anthropic's most capable frontier model family.",
    description:
      "Claude is Anthropic's family of frontier models built for deep reasoning, long-context work, and agentic coding. The Opus tier targets the hardest tasks.",
    image_url: null,
    homepage_url: "https://www.anthropic.com",
    current_version: "4.8",
    accent_color: "violet",
    is_featured: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: "t-gemini",
    slug: "gemini",
    name: "Gemini",
    category: "Frontier Models",
    tagline: "Google DeepMind's multimodal model line.",
    description:
      "A natively multimodal frontier model family spanning text, image, audio, and video understanding.",
    image_url: null,
    homepage_url: "https://deepmind.google/technologies/gemini/",
    current_version: "2.5",
    accent_color: "cyan",
    is_featured: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: "t-llama",
    slug: "llama",
    name: "Llama",
    category: "Frontier Models",
    tagline: "Meta's open-weight model family.",
    description:
      "Open-weight large language models from Meta, popular for self-hosted and fine-tuned deployments.",
    image_url: null,
    homepage_url: "https://www.llama.com",
    current_version: "4",
    accent_color: "emerald",
    is_featured: false,
    created_at: now,
    updated_at: now,
  },
  {
    id: "t-typescript",
    slug: "typescript",
    name: "TypeScript",
    category: "Languages",
    tagline: "JavaScript with syntax for types.",
    description:
      "A strongly typed superset of JavaScript that compiles to plain JavaScript, maintained by Microsoft.",
    image_url: null,
    homepage_url: "https://www.typescriptlang.org",
    current_version: "5.8",
    accent_color: "cyan",
    is_featured: false,
    created_at: now,
    updated_at: now,
  },
  {
    id: "t-rust",
    slug: "rust",
    name: "Rust",
    category: "Languages",
    tagline: "Performance and memory safety, without a GC.",
    description:
      "A systems programming language focused on safety, speed, and fearless concurrency.",
    image_url: null,
    homepage_url: "https://www.rust-lang.org",
    current_version: "1.88",
    accent_color: "emerald",
    is_featured: false,
    created_at: now,
    updated_at: now,
  },
  {
    id: "t-python",
    slug: "python",
    name: "Python",
    category: "Languages",
    tagline: "The lingua franca of AI and scripting.",
    description:
      "A high-level, dynamically typed language that dominates data science, ML, and automation.",
    image_url: null,
    homepage_url: "https://www.python.org",
    current_version: "3.14",
    accent_color: "violet",
    is_featured: false,
    created_at: now,
    updated_at: now,
  },
  {
    id: "t-next",
    slug: "nextjs",
    name: "Next.js",
    category: "Frameworks",
    tagline: "The React framework for the web.",
    description:
      "A full-stack React framework with the App Router, server components, and first-class SSR/ISR.",
    image_url: null,
    homepage_url: "https://nextjs.org",
    current_version: "15.1",
    accent_color: "cyan",
    is_featured: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: "t-react",
    slug: "react",
    name: "React",
    category: "Frameworks",
    tagline: "The library for web and native user interfaces.",
    description:
      "A declarative, component-based library for building UIs, now with Server Components and Actions.",
    image_url: null,
    homepage_url: "https://react.dev",
    current_version: "19",
    accent_color: "violet",
    is_featured: true,
    created_at: now,
    updated_at: now,
  },
];

export const mockUpdates: Update[] = [
  {
    id: "u-1",
    technology_id: "t-claude",
    title: "Claude Opus 4.8 released with a 1M-token context window",
    summary:
      "Expanded long-context reasoning and stronger agentic coding performance across the board.",
    version: "4.8",
    importance: 5,
    source_url: "https://www.anthropic.com/news",
    published_at: "2026-06-29T12:00:00.000Z",
    created_at: now,
  },
  {
    id: "u-2",
    technology_id: "t-next",
    title: "Next.js 15.1 improves the App Router and caching defaults",
    summary: "Refined ISR semantics and faster cold starts for server components.",
    version: "15.1",
    importance: 4,
    source_url: "https://nextjs.org/blog",
    published_at: "2026-06-28T09:30:00.000Z",
    created_at: now,
  },
  {
    id: "u-3",
    technology_id: "t-gemini",
    title: "Gemini 2.5 adds extended multimodal tool use",
    summary: "Native video understanding and improved function-calling reliability.",
    version: "2.5",
    importance: 4,
    source_url: "https://blog.google",
    published_at: "2026-06-27T15:45:00.000Z",
    created_at: now,
  },
  {
    id: "u-4",
    technology_id: "t-react",
    title: "React 19 stabilizes Actions and the use() hook",
    summary: "Form Actions and async transitions graduate to stable.",
    version: "19",
    source_url: "https://react.dev/blog",
    published_at: "2026-06-26T11:00:00.000Z",
    created_at: now,
  },
  {
    id: "u-5",
    technology_id: "t-claude",
    title: "Claude adds faster output mode for coding workflows",
    summary: "Lower-latency responses on Opus without downgrading model quality.",
    version: "4.8",
    source_url: "https://www.anthropic.com/news",
    published_at: "2026-06-25T10:15:00.000Z",
    created_at: now,
  },
  {
    id: "u-6",
    technology_id: "t-next",
    title: "Turbopack becomes the default dev bundler",
    summary: "Significantly faster local dev startup and hot reloads.",
    version: "15.1",
    source_url: "https://nextjs.org/blog",
    published_at: "2026-06-24T08:00:00.000Z",
    created_at: now,
  },
  {
    id: "u-7",
    technology_id: "t-gemini",
    title: "Gemini API lowers free-tier latency",
    summary: "Infrastructure upgrades cut median response times on the free tier.",
    version: null,
    source_url: "https://ai.google.dev",
    published_at: "2026-06-23T14:20:00.000Z",
    created_at: now,
  },
  {
    id: "u-8",
    technology_id: "t-react",
    title: "React Compiler reaches release candidate",
    summary: "Automatic memoization removes most manual useMemo/useCallback.",
    version: null,
    source_url: "https://react.dev/blog",
    published_at: "2026-06-22T13:00:00.000Z",
    created_at: now,
  },
  {
    id: "u-9",
    technology_id: "t-typescript",
    title: "TypeScript 5.8 ships faster project references",
    summary: "Build performance improvements for large monorepos.",
    version: "5.8",
    source_url: "https://devblogs.microsoft.com/typescript/",
    published_at: "2026-06-21T09:00:00.000Z",
    created_at: now,
  },
  {
    id: "u-10",
    technology_id: "t-rust",
    title: "Rust 1.88 stabilizes async closures",
    summary: "Long-awaited ergonomic improvement for async-heavy codebases.",
    version: "1.88",
    source_url: "https://blog.rust-lang.org",
    published_at: "2026-06-20T16:30:00.000Z",
    created_at: now,
  },
  {
    id: "u-11",
    technology_id: "t-python",
    title: "Python 3.14 improves the free-threaded build",
    summary: "Further progress on removing the GIL for true parallelism.",
    version: "3.14",
    source_url: "https://www.python.org/downloads/",
    published_at: "2026-06-19T12:10:00.000Z",
    created_at: now,
  },
  {
    id: "u-12",
    technology_id: "t-llama",
    title: "Llama 4 expands the open-weight lineup",
    summary: "New sizes optimized for on-device and edge inference.",
    version: "4",
    source_url: "https://www.llama.com",
    published_at: "2026-06-18T10:00:00.000Z",
    created_at: now,
  },
];

export const mockOpportunities: Opportunity[] = [
  {
    id: "o-1",
    slug: "smart-india-hackathon-2026",
    title: "Smart India Hackathon 2026",
    kind: "hackathon",
    organizer: "Govt. of India",
    description:
      "India's largest nationwide hackathon where student teams solve real problems posed by ministries and industry.",
    location: "Pan-India",
    country: "India",
    is_remote: false,
    eligibility: "College students (teams of 6)",
    prize: "₹1,00,000 per problem",
    deadline: "2026-09-15T18:30:00.000Z",
    starts_at: "2026-12-01T03:30:00.000Z",
    source_url: "https://www.sih.gov.in/",
    image_url: null,
    tags: ["beginner-friendly", "india", "students"],
    accent_color: "violet",
    is_curated: true,
    is_featured: true,
    published_at: now,
    created_at: now,
    updated_at: now,
  },
  {
    id: "o-2",
    slug: "aws-reinvent-2026",
    title: "AWS re:Invent 2026",
    kind: "conference",
    organizer: "AWS",
    description:
      "Amazon Web Services' flagship global cloud & AI conference — keynotes, hands-on labs, and certifications.",
    location: "Las Vegas, USA",
    country: "USA",
    is_remote: false,
    eligibility: "Open to all — students get discounted passes",
    prize: null,
    deadline: "2026-11-20T06:00:00.000Z",
    starts_at: "2026-11-30T06:00:00.000Z",
    source_url: "https://aws.amazon.com/events/reinvent/",
    image_url: null,
    tags: ["cloud", "ai", "certification"],
    accent_color: "emerald",
    is_curated: true,
    is_featured: true,
    published_at: now,
    created_at: now,
    updated_at: now,
  },
  {
    id: "o-3",
    slug: "mlh-fellowship-2026",
    title: "MLH Fellowship",
    kind: "internship",
    organizer: "Major League Hacking",
    description:
      "A remote internship alternative — contribute to open source with mentorship over 12 weeks.",
    location: "Remote",
    country: "Global",
    is_remote: true,
    eligibility: "Students & freshers worldwide",
    prize: "Stipend",
    deadline: "2026-07-31T03:59:00.000Z",
    starts_at: null,
    source_url: "https://fellowship.mlh.io/",
    image_url: null,
    tags: ["open-source", "remote", "mentorship"],
    accent_color: "emerald",
    is_curated: true,
    is_featured: true,
    published_at: now,
    created_at: now,
    updated_at: now,
  },
  {
    id: "o-4",
    slug: "ethindia-2026",
    title: "ETHIndia 2026",
    kind: "hackathon",
    organizer: "Devfolio",
    description:
      "The world's largest Ethereum hackathon — build web3 projects with mentors and ship in 36 hours.",
    location: "Bengaluru, India",
    country: "India",
    is_remote: false,
    eligibility: "Open to students & developers",
    prize: "$50,000+ pool",
    deadline: "2026-11-01T18:30:00.000Z",
    starts_at: "2026-12-05T03:30:00.000Z",
    source_url: "https://ethindia.co/",
    image_url: null,
    tags: ["web3", "blockchain", "india"],
    accent_color: "cyan",
    is_curated: true,
    is_featured: false,
    published_at: now,
    created_at: now,
    updated_at: now,
  },
  {
    id: "o-5",
    slug: "google-summer-of-code-2026",
    title: "Google Summer of Code 2026",
    kind: "internship",
    organizer: "Google",
    description:
      "A global program pairing new contributors with open-source orgs for a paid summer of coding.",
    location: "Remote",
    country: "Global",
    is_remote: true,
    eligibility: "Newcomers to open source (18+)",
    prize: "Stipend (₹/$ by region)",
    deadline: "2026-04-08T18:00:00.000Z",
    starts_at: null,
    source_url: "https://summerofcode.withgoogle.com/",
    image_url: null,
    tags: ["open-source", "remote", "paid"],
    accent_color: "violet",
    is_curated: true,
    is_featured: false,
    published_at: now,
    created_at: now,
    updated_at: now,
  },
  {
    id: "o-6",
    slug: "google-io-2026",
    title: "Google I/O 2026",
    kind: "conference",
    organizer: "Google",
    description:
      "Google's annual developer conference covering Android, AI (Gemini), web, and cloud.",
    location: "Mountain View, USA + Online",
    country: "Global",
    is_remote: true,
    eligibility: "Open to all developers — free online",
    prize: null,
    deadline: null,
    starts_at: "2026-05-12T17:00:00.000Z",
    source_url: "https://io.google/",
    image_url: null,
    tags: ["ai", "android", "web"],
    accent_color: "cyan",
    is_curated: true,
    is_featured: false,
    published_at: now,
    created_at: now,
    updated_at: now,
  },
];
